language: php

sudo: required

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  include:
    - php: 5.5.9
      env: setup=lowest
    - php: 5.5.9
      env: setup=stable

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi

before_script:
  - sudo apt-get install libsodium libsodium-dev
  - pecl install libsodium

script: vendor/bin/phpunit