language: php

sudo: required

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - sudo add-apt-repository ppa:anton+/dnscrypt -y
  - sudo apt-get update -q
  - sudo apt-get install libsodium
  - pecl install libsodium

script: vendor/bin/phpunit